name: Deploy

on: push

jobs:
    build:
        name: Build front and backend images
        if: contains( github.ref, 'master')
        runs-on: [self-hosted]

        steps:
            - uses: actions/checkout@v2
              with:
                  persist-credentials: false

            - name: Build images
              working-directory: ${{runner.workspace}}/personal-website
              run: docker-compose build front api
              
            - name: Set network
              run: docker network create loc
              
            - name: Deploy
              working-directory: ${{runner.workspace}}/personal-website
              run: docker-compose up -d
